---
apiVersion: apps/v1
kind: Deployment
#kind: DaemonSet
metadata:
  name: airship-host-config
spec:
  replicas: 3
  selector:
    matchLabels:
      name: airship-host-config
  template:
    metadata:
      labels:
        name: airship-host-config
    spec:
      serviceAccountName: airship-host-config
      nodeSelector:
        node-type: controlplane
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      initContainers:
       - name: data
         image: busybox
         command: ['sh','-c','chown 1001:0 /opt/ansible/data']
         volumeMounts:
          - name : data
            mountPath: /opt/ansible/data
      containers:
        - name: airship-host-config
          # Replace this with the built image name
          image: "quay.io/sirishagopigiri/airship-host-config:updated_status"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/root/runner
            name: runner
          - mountPath: /opt/ansible/data
            name: data
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "airship-host-config"
            - name: ANSIBLE_FILTER_PLUGINS
              value: /opt/ansible/plugins/filter
            - name: ANSIBLE_FORKS
              value: "100"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_INVENTORY
              value: /opt/ansible/inventory
            - name: USER
              value: "vagrant"
            - name: PASS
              value: "testing"
            - name: SECRET_NAMESPACE
              value: "default"
              #      securityContext:
              #          runAsUser: 1001
              #          runAsGroup: 1001
              #          fsGroup: 1001
      volumes:
        - name: runner
          emptyDir: {}
        - name: data
          hostPath:
             path: /root/data
             type: DirectoryOrCreate
