---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airship-host-config
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airship-host-config
  template:
    metadata:
      labels:
        name: airship-host-config
    spec:
      serviceAccountName: airship-host-config
      nodeSelector:
        node-type: controlplane
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: airship-host-config
          # Replace this with the built image name
          image: "AIRSHIP_HOSTCONFIG_IMAGE"
          imagePullPolicy: "PULL_POLICY"
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "airship-host-config"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_INVENTORY
              value: /opt/ansible/inventory
            - name: USER
              value: "USERNAME"
            - name: PASS
              value: "PASSWORD"
      volumes:
        - name: runner
          emptyDir: {}
